dnsSuffix: kubernetes.docker.internal
clusterIP: TBA
storageClass: standard
namespaces:
 - vault
 - ingress-nginx
 - monitoring
 - kafka
 - argocd
 - grafana
 - otel-collector
 - cert-manager
 - victoria-metrics

caCert: |
  -----BEGIN CERTIFICATE-----
  MIIFATCCAumgAwIBAgIUNuf1c9Ko/+siQZejNdhV+aVtMB4wDQYJKoZIhvcNAQEL
  BQAwEDEOMAwGA1UEAwwFcGF1bGMwHhcNMjUxMjE2MTI0NTM1WhcNMzUxMjE0MTI0
  NTM1WjAQMQ4wDAYDVQQDDAVwYXVsYzCCAiIwDQYJKoZIhvcNAQEBBQADggIPADCC
  AgoCggIBANmGuEgwkpnYkApTXAcGGwhsuqIqGBUxN7+GPYoni+2lYILHDat7CY6c
  bOCDdlIXIDI2Lxv5slHJyTCLg1kEHi/0KVEVuKCn3LsGoCK3uKQcBQ/2s2EZ7EN8
  rzV6nsCockvZav4zWAOu5Kyj2z++aQWn8/7NaWnA/NbJAZINxk390YYSaGZVdkT0
  DrZ7xR6uJWXeH7VdxCDBXAF/8mNdyEIsA9/ixRvBExoKUak8If1CYobLJq9XiEmi
  1xOp5KUQVgSTwlAbVP8rNSabBNFpJmDQf2lVGgiylWfQxGqfylR/coKSFrmY6jvH
  mmeOdHL8RDQpHOxBmpXKtLTLgOIgw6XBG7BzSAm23YV/e2WatT0G0BfQ0y2H+sJH
  8xS7u/GaHWmaohR+DgbKcq26B8w+Z7o+gtAvdVeToWcUy25QkugDW1ufiWyzvA7P
  79embib0G2SqUcY1ygxYnx3B8zd0FtJZTIT90s7tDYKMCDJcz/XbZAbDU+UoDH0E
  +Ys1qPRt58y5xVU7516yucN0Y/kmoSCfWMQ04dx9OLeZG5JnsFHhl1y94IVyZbUy
  FujKc/2m/kuIjWfl/6Jn20F9mdK2L9/RcOt+hHLKbYu1jCpMQqWKaZa8k8FuYHDX
  eAQZ7UNqu/El0SteiMot64E6SBZaoRlBy6kBWpTPtVvLNoiFwQbnAgMBAAGjUzBR
  MB0GA1UdDgQWBBSvEWtByEdbr644G5ItZHBOrGUJuDAfBgNVHSMEGDAWgBSvEWtB
  yEdbr644G5ItZHBOrGUJuDAPBgNVHRMBAf8EBTADAQH/MA0GCSqGSIb3DQEBCwUA
  A4ICAQA1GQAJ7L7L0bz0KMURgNBmhnvMAmVMhxXNcwKXEkhjrhRucCO05W1cU0jo
  idJrPGq3tySRDwU0+Z/B5odHlmmb8cr8pKQtTWRw+ecZMjW/VOcakcMSTpMnToOy
  g2NqYhLOd1Ia7je+op0nRcdUKsnkYfTHEzxSo3iXJjH/jOdB4pYR409YqfkqnYqa
  5cigYDC8dmhoLeANa52BwYjslXdfiZZEi1x0mS3noOF2eTHsoKbEEiuEQk92QtMO
  7/azKck0FoDeL4PBu1mL1DplhoZ2OLYoThCW2LfZ8V0Uygcra3jIEzFeW7DGH5fY
  sw2ZYklqQpvDQKV65RAW5A0Opm0TwusMfDtvPBKwQ5It/tOhRleeO+mia0GGrZE3
  Nryl750bl5J8jB8wSgvP0rhZh6J5ta5N8AYfzkH037lq9iYWTRaIORZXrZMV7ajS
  gOHWrYWaBvidxOivvJrCMa9re6njSCdIDcYOFzXmS3LsSEXYUAesMvt/QukSHudD
  Z5vcf9DNhWyvDwBZoEbGOWYAYimCHR6lHQ7tQUvqFcgqpCMDj2Fe4FKbzdXZEo4V
  uxSwrITlt+GqRTZeRetsBFTXl0sXH/gyNKVlUE6w3yyElEOyywKyTlNslHfOgNVL
  IV1vOY7wOi+h5WaHoSAhorr6r+Vy/UmO14xExWOOSZkmlXWf3A==
  -----END CERTIFICATE-----
