dnsSuffix: observability.kubernetes.internal
clusterIP: TBA
storageClass: standard
namespaces:
 - vault
 - ingress-nginx
 - monitoring
 - kafka
 - argocd
 - grafana
 - otel-collector
 - cert-manager
 - victoria-metrics
 - splunk
caCert: |
  -----BEGIN CERTIFICATE-----
  MIIFETCCAvmgAwIBAgIUB3PRsiDUxSlu8XGBOi5CqKuF8TIwDQYJKoZIhvcNAQEL
  BQAwGDEWMBQGA1UEAwwNb2JzZXJ2YWJpbGl0eTAeFw0yNTEyMTYxNzM5MTBaFw0z
  NTEyMTQxNzM5MTBaMBgxFjAUBgNVBAMMDW9ic2VydmFiaWxpdHkwggIiMA0GCSqG
  SIb3DQEBAQUAA4ICDwAwggIKAoICAQCsiaxJ2SCtXOUUiioZGZlHIstzOfeDJo8l
  eEohWyU9FXVcl+Q0dusR6VPrnyI+cCH/o6ETmyXKdliFYrtQpZEYFe5cgc4dp+8H
  IB5s7omcY1mHPIXJygffd1C8aJrM9S54SwzX3R2msUhfxLJAtdeAE6pHGkpOVShJ
  PyigOmP0EarzaJ3WOoHmUrIGB315JtgMAjw0sCIrIuqVQvmy+RBwGe5dnwhbt/rO
  r0YZ9jxOa6mfepfTkCgNrk3yznKgJ23FAhpS37EywsJ4aDmj1l6fH2xfpegskQli
  WTI1g6wfOjm1VsvDvW5nKi0FVU+ItnednMlYwhLru0zo22KpTfGT/SekpBnSIyNC
  584h4XupV+xW11QYdd9m/lYGcoH7ajxKvGI1pWGmDn+3LburpggVT+J3TPo7o6im
  eYPtWtZIOv512iWVUCdL7E6zJUA39t4A6JsRaC1v+9U3TOPA8EuTYeORphq5dV9e
  uYK3GaBLJ6n6IvVOzkAxO2WFRGnxyRmBFYK/4rdxiZBe8QYMOFYe10drHiUohiCx
  QGwErUmanwsxxSK18rQAc85jqoZdYyyZKvlMFTbXhoHajqxCa4G+pjOWU6WpzHs4
  g1uKUxOXKZvV9tW8/xvWSvD15y0VN6XHsyV35wPNMkipMl+M3G2zQiQENwKmhxkn
  xJpkM6FsAwIDAQABo1MwUTAdBgNVHQ4EFgQUENpercM7HUy0GsJPCcuhqKivUF0w
  HwYDVR0jBBgwFoAUENpercM7HUy0GsJPCcuhqKivUF0wDwYDVR0TAQH/BAUwAwEB
  /zANBgkqhkiG9w0BAQsFAAOCAgEATTxw3LqooaXKUfhQ1uG1DKnV2DGTJKwFNz6n
  EhKkrNalqt3Wsxjgz3DOe+Pc+xnJ6pI8Xl9IA4hksMy4NP3pq/DBy6u6UzUvkkcr
  qz8LHNZ/xCTeKYFv4lNI2JQ0bsbNMOcHCepaHFq0klPBSTruiWRg6WGssNSW0xbF
  ITcmGmosgMI+3cNK/wr/Yr7BiFmuLqyaMIaFQxxANxNEYiJgp0ZYiVlg4X36YIfF
  H6xxwe8/qodbO/aRuEc9FnuCFKwh+4zbEGKjgAzP/UoUaEEfSuY/VXtLEShGelw9
  KkTBlS76Zvy148zbMcRDOpmJoQSvsae/k4+v4keADjhzhq8x9L4tH8tn18vZewSC
  AG4ODi6LMZyoubojESVEyPgeeyNSkAhmbH76OaqSfF8oLW/H89387FfnaVfuHUvY
  47M2RhlqTPge/v3tDPR1rfCqNBptYYLv6kPDE6b8qJdCSrNAZHbKSoE/vIuHdZwV
  8MBzV5sAs1Q+1vt8CyxLEOhbr0oIyDx4M0BzBIF+7UwuTgn6PmbDuA5C1p5n08eN
  72GKZN7g2VmOKn9xbM/bgUuw4idpKXYRj8NxHxfcv4C2JtiU+0YWBh7TXO33JVe8
  vjomk30zslMYOGGTnbZVmsnnLf0PbX6wsAGuspsWIMS5PtEJX9r8YvyMpzVNHeDT
  qj9gA6Q=
  -----END CERTIFICATE-----
